# Generated by Django 4.2 on 2025-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_admin_address_admin_phone_admin_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Restaurant', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('default_order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('enable_notifications', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Restaurant Settings',
                'managed': True,
            },
        ),
    ]
