# Generated by Django 4.2 on 2025-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Desserts', 'Desserts'), ('Main Course', 'Main Course'), ('Beverages', 'Beverages')], max_length=50, unique=True),
        ),
    ]
