# Generated by Django 4.2 on 2025-04-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_order_item_count_remove_order_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('status_update', 'Status Update')], default='new_order', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order'),
        ),
    ]
