# Generated by Django 4.2 on 2025-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_order_options_order_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
