# Generated by Django 4.2 on 2025-05-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_payment_method_remove_payment_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
