# Generated by Django 4.2 on 2025-05-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
