# Generated by Django 4.2 on 2025-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_orderitem_menu_item_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
