# Generated by Django 4.2 on 2025-05-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='reset',
            new_name='password',
        ),
    ]
